First sprint
ClevertecFrontendLab/sprint1-GorbunovaAnna pull request #1
Opened 2023-01-31 18:58 UTC by GorbunovaAnna

2023-01-31 19:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675191622/content-window.png)

2023-01-31 19:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/GorbunovaAnna/1675192603/content-window.png)

2023-01-31 19:22 UTC, klichkovskiy requested changes
Сделай согласно макету. Проверь все приложение на горизонтальный скролл!

2023-01-31 19:22 UTC, klichkovskiy commented on declarations.d.ts
> +//   }
Удалить закомментированный код по всему приложению

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +export const MainPage = () => (
![image](https://user-images.githubusercontent.com/62481116/215860732-ad8ad090-c2b2-4435-a215-18fd2d8bbf67.png)
Добавить постоянные отступы, удалить горизонтальный скролл

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +export const MainPage = () => (
![image](https://user-images.githubusercontent.com/62481116/215860934-85efac1b-4ccd-40e2-8604-0e0edba3fe1b.png)
убрать

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +export const MainPage = () => (
Убрать горизонтальный скролл по всему приложению!

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +          <BreadCrumbs book={book} />
![image](https://user-images.githubusercontent.com/62481116/215861218-7d504c90-97c8-4aed-90e4-2862abe15446.png)
сделай по макету

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                  <h5 className={styles.subTitle}>О книге</h5>
Это просто текст, не заголовок

2023-01-31 19:22 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +            <div className={styles.additionalInfo}>
![image](https://user-images.githubusercontent.com/62481116/215861421-452986d5-5570-4e0d-8713-2de01ee5f50e.png)
сделать по макету

2023-02-01 18:31 UTC, GorbunovaAnna commented on src/pages/book/book-page.tsx
> +                  <h5 className={styles.subTitle}>О книге</h5>
Здесь же как раз много описаний и они имеют заголовоки

2023-02-01 19:09 UTC, klichkovskiy approved these changes

2023-02-01 19:11 UTC, merged